### ISSUE TITLE
pack jar from jar-dependencies as packed jars

### ISSUE THREAD

**Issue by mkristian** [jruby-gradle/jruby-gradle-storm-plugin#6]
it kind of difficult to load some jars via jar-dependencies and some other jars should not be loaded.

jruby comes with couple of jars with its default gems: jline-2.11.jar, those bouncy-castle jars. jruby-9k will come with snakeyaml-1.14.jar and maybe one or more other jars soon.

AND there is no way to find out which jars jruby bundles with those default gems (any ideas on how to expose those extra dependencies formally are welcome).

now jar-dependencies loads those jars. it will look on "classpath" or "classloader" first.

with maven I just use http://maven.apache.org/plugins/maven-dependency-plugin/copy-dependencies-mojo.html, set useRepositoryLayout=true and outputDirectory=target/classes and the artifact will have those jars where jar-dependencies is going to look for them.

**Comment by rtyler** [comment]
This should be solved by the work I'm doing to have `JRubyStorm` depend on `JRubyJar` instead of relying on `Shadowjar` for packing topology jars
